dependencies:
  - name: insightedge-manager
    version: "15.0.0-m16"
    repository: file://../insightedge-manager
    alias: manager
  - name: insightedge-pu
    version: "15.0.0-m16"
    repository: file://../insightedge-pu
    alias: pu
  - name: insightedge-zeppelin
    version: "15.0.0-m16"
    repository: file://../insightedge-zeppelin
    alias: zeppelin

