{
 "title": "Space-demo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Entries",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Entries" }
   ],
   "targets": [
    {
     "fields": [
      { "func": "sum", "name": "value" }
     ],
     "measurement": "space_data_entries_total",
     "query": "SELECT sum(value) FROM \"space_data_entries_total\" WHERE space_name='demo' AND space_active='true' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "space_name", "operator": "=", "value": "demo" },
      { "key": "space_active", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Active Transactions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Transactions" }
   ],
   "targets": [
    {
     "fields": [
      { "func": "sum", "name": "value" }
     ],
     "measurement": "space_transactions_active",
     "query": "SELECT sum(value) FROM \"space_transactions_active\" WHERE space_name='demo' AND space_active='true' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "space_name", "operator": "=", "value": "demo" },
      { "key": "space_active", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Active Incoming Connections",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "fields": [
      { "func": "sum", "name": "value" }
     ],
     "measurement": "space_connections_incoming_active",
     "query": "SELECT sum(value) FROM \"space_connections_incoming_active\" WHERE space_name='demo' AND space_active='true' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "space_name", "operator": "=", "value": "demo" },
      { "key": "space_active", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Replication Redo Log Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Packets" }
   ],
   "targets": [
    {
     "fields": [
      { "func": "sum", "name": "value" }
     ],
     "measurement": "space_replication_redo-log_size",
     "query": "SELECT sum(value) FROM \"space_replication_redo-log_size\" WHERE space_name='demo' AND space_active='true' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "space_name", "operator": "=", "value": "demo" },
      { "key": "space_active", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  { "title": "Space Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Write Operations",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Operations" }
   ],
   "targets": [
    {
     "fields": [
      { "func": "sum", "name": "value" }
     ],
     "measurement": "space_operations_write-tp",
     "query": "SELECT sum(value) FROM \"space_operations_write-tp\" WHERE space_name='demo' AND space_active='true' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "space_name", "operator": "=", "value": "demo" },
      { "key": "space_active", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Read Operations",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Operations" }
   ],
   "targets": [
    {
     "fields": [
      { "func": "sum", "name": "value" }
     ],
     "measurement": "space_operations_read-tp",
     "query": "SELECT sum(value) FROM \"space_operations_read-tp\" WHERE space_name='demo' AND space_active='true' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "space_name", "operator": "=", "value": "demo" },
      { "key": "space_active", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Take Operations",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Operations" }
   ],
   "targets": [
    {
     "fields": [
      { "func": "sum", "name": "value" }
     ],
     "measurement": "space_operations_take-tp",
     "query": "SELECT sum(value) FROM \"space_operations_take-tp\" WHERE space_name='demo' AND space_active='true' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "space_name", "operator": "=", "value": "demo" },
      { "key": "space_active", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Change Operations",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Operations" }
   ],
   "targets": [
    {
     "fields": [
      { "func": "sum", "name": "value" }
     ],
     "measurement": "space_operations_change-tp",
     "query": "SELECT sum(value) FROM \"space_operations_change-tp\" WHERE space_name='demo' AND space_active='true' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "space_name", "operator": "=", "value": "demo" },
      { "key": "space_active", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Execute Operations",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Operations" }
   ],
   "targets": [
    {
     "fields": [
      { "func": "sum", "name": "value" }
     ],
     "measurement": "space_operations_execute-tp",
     "query": "SELECT sum(value) FROM \"space_operations_execute-tp\" WHERE space_name='demo' AND space_active='true' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "space_name", "operator": "=", "value": "demo" },
      { "key": "space_active", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Notify Operations",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Operations" }
   ],
   "targets": [
    {
     "fields": [
      { "func": "sum", "name": "value" }
     ],
     "measurement": "space_operations_before-listener-trigger-tp",
     "query": "SELECT sum(value) FROM \"space_operations_before-listener-trigger-tp\" WHERE space_name='demo' AND space_active='true' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "space_name", "operator": "=", "value": "demo" },
      { "key": "space_active", "operator": "=", "value": "true" }
     ]
    }
   ]
  }
 ]
}