FROM gigaspaces/insightedge-enterprise:14.5

COPY flightdelays20172018.csv /opt/gigaspaces/
COPY weather2017_8.csv /opt/gigaspaces/
COPY zeppelin/notebook/INSIGHTEDGE-GETTING-STARTED /opt/gigaspaces/insightedge/zeppelin/notebook/INSIGHTEDGE-GETTING-STARTED
COPY zeppelin/notebook/INSIGHTEDGE-GETTING-STARTED-2 /opt/gigaspaces/insightedge/zeppelin/notebook/INSIGHTEDGE-GETTING-STARTED-2
COPY zeppelin/conf/interpreter.json /opt/gigaspaces/insightedge/zeppelin/conf/
