# Default values for xap-zeppelin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: yoramw/insightedge-enterprise
  tag: "15.0.0-m16"
  pullPolicy: Always

nameOverride: insightedge-zeppelin

kafka:
  url: localhost:9092

service:
  # type: Service type.
  type: LoadBalancer
  ports:
    # api: REST Manager API port.
    api:
      port: 9090
      nodePort:
