
apiVersion: v1
kind: Service
metadata:
  name: {{ template "insightedge-zeppelin.fullname" . }}-service
  labels:
    app: {{ template "insightedge-zeppelin.name" . }}
    chart: {{ template "insightedge-zeppelin.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: zeppelin
      protocol: TCP
      port: {{ .Values.service.ports.api.port }}
      {{if (.Values.service.ports.api.nodePort)}}
      nodePort: {{ .Values.service.ports.api.nodePort }}
      {{ end }}
  selector:
    selectorId: {{ template "insightedge-zeppelin.fullname" . }}
