
apiVersion: v1
kind: Service
metadata:
  name: {{ template "insightedge-manager.fullname" . }}-service
  labels:
    app: {{ template "insightedge-manager.name" . }}
    chart: {{ template "insightedge-manager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: api
      protocol: TCP
      port: {{ .Values.service.ports.api.port }}
      {{if (.Values.service.ports.api.nodePort)}}
      nodePort: {{ .Values.service.ports.api.nodePort }}
      {{ end }}
    {{if (.Values.enableExternalClient) }}
    - name: lus
      protocol: TCP
      port: {{ .Values.service.ports.lus.port }}
      nodePort: {{ .Values.service.ports.lus.port }}
    - name: lrmi1
      protocol: TCP
      port: 30820
      nodePort: 30820
    - name: lrmi2
      protocol: TCP
      port: 30821
      nodePort: 30821
    {{end}}
  selector:
    selectorId: {{ template "insightedge-manager.fullname" . }}
